name: Deploy Backend

on:
  push:
    branches:
      - feat/prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/projects/backend

            git pull origin feat/prod

            npm install
            pm2 restart backend